# Analizden hariç tutulacak yaygın ve gürültüye neden olan sınıflar
STOP_CLASSES = frozenset([
    "Ljava/lang/Object;", "Ljava/lang/String;", "Ljava/lang/StringBuilder;",
    "Ljava/lang/StringBuffer;", "Ljava/lang/Class;", "Ljava/lang/System;",
    "Ljava/util/ArrayList;", "Ljava/util/List;", "Ljava/util/Map;",
    "Ljava/util/HashMap;", "Ljava/util/HashSet;", "Ljava/util/Set;",
    "Ljava/util/Iterator;", "Ljava/util/Collection;", "Ljava/util/Arrays;",
    "Ljava/util/Collections;", "Ljava/util/Date;", "Ljava/util/Calendar;",
    "Ljava/lang/Exception;", "Ljava/lang/Throwable;", "Ljava/lang/Error;",
    "Ljava/lang/RuntimeException;", "Ljava/lang/Integer;", "Ljava/lang/Long;",
    "Ljava/lang/Float;", "Ljava/lang/Double;", "Ljava/lang/Boolean;",
    "Ljava/lang/Byte;", "Ljava/lang/Short;", "Ljava/lang/Character;",
    "Ljava/lang/Number;", "Ljava/lang/Math;", "Ljava/lang/Thread;",
    "Ljava/lang/Runnable;", "Ljava/io/Serializable;", "Ljava/io/IOException;",
    "Ljava/io/InputStream;", "Ljava/io/OutputStream;", "Ljava/io/Reader;",
    "Ljava/io/Writer;", "Ljava/io/BufferedReader;", "Ljava/io/BufferedWriter;",
    "Ljava/io/PrintWriter;", "Ljava/io/Closeable;",
    "Ljava/lang/annotation/Annotation;", "Ljava/lang/Enum;",
    "Ljava/text/SimpleDateFormat;", "Ljava/text/DateFormat;",
    "Landroid/os/Bundle;", "Landroid/os/Parcel;", "Landroid/os/Parcelable;",
    "Landroid/os/Handler;", "Landroid/os/Message;", "Landroid/os/Looper;",
    "Landroid/content/Context;", "Landroid/content/res/Resources;",
    "Landroid/content/res/Configuration;", "Landroid/util/Log;",
    "Landroid/util/DisplayMetrics;", "Landroid/util/TypedValue;",
    "Landroid/view/View;", "Landroid/view/ViewGroup;", "Landroid/view/LayoutInflater;",
    "Landroid/widget/TextView;", "Landroid/widget/Button;", "Landroid/widget/EditText;",
    "Landroid/widget/ImageView;", "Landroid/widget/LinearLayout;",
    "Landroid/widget/RelativeLayout;", "Landroid/widget/FrameLayout;",
    "Landroid/widget/Toast;", "Landroid/app/Activity;", "Landroid/app/Fragment;",
    "Landroid/app/Application;", "Landroid/app/Dialog;",
    "Landroidx/appcompat/app/AppCompatActivity;",
    "Landroidx/fragment/app/Fragment;", "Landroidx/fragment/app/FragmentActivity;",
    "Landroidx/recyclerview/widget/RecyclerView;",
    "Landroidx/viewpager/widget/ViewPager;",
    "Landroid/support/v7/app/AppCompatActivity;",
    "Landroid/support/v4/app/Fragment;", "Landroid/support/v4/app/FragmentActivity;",
    "Lcom/google/android/material/", "Landroidx/constraintlayout/",
    "Landroidx/lifecycle/", "Landroidx/core/",
    "Lcom/google/gson/", "Lorg/json/JSONObject;", "Lorg/json/JSONArray;",
    "Ljava/util/concurrent/", "Ljava/util/regex/Pattern;",
    "Landroid/graphics/Bitmap;", "Landroid/graphics/Canvas;",
    "Landroid/graphics/Paint;", "Landroid/graphics/Color;",
    "Landroid/graphics/drawable/Drawable;", "Landroid/text/TextUtils;",
    "Landroid/view/MotionEvent;", "Landroid/view/KeyEvent;",
    "Landroid/view/ViewTreeObserver;", "Landroid/animation/",
    "Lkotlin/jvm/internal/", "Lkotlin/Metadata;",
])

# Yüksek riskli ve doğrudan skoru etkileyen tehlikeli izinler
DANGEROUS_PERMISSIONS = frozenset([
    "SEND_SMS", "READ_SMS", "RECEIVE_SMS", "WRITE_SMS",
    "READ_PHONE_STATE", "CALL_PHONE", "READ_CALL_LOG", "WRITE_CALL_LOG",
    "ADD_VOICEMAIL", "USE_SIP", "PROCESS_OUTGOING_CALLS",
    "ANSWER_PHONE_CALLS", "READ_PHONE_NUMBERS",
    "BIND_DEVICE_ADMIN", "SYSTEM_ALERT_WINDOW",
    "BIND_ACCESSIBILITY_SERVICE", "BIND_NOTIFICATION_LISTENER_SERVICE",
    "REQUEST_IGNORE_BATTERY_OPTIMIZATIONS", "WRITE_SETTINGS", "WRITE_SECURE_SETTINGS",
    "INSTALL_PACKAGES", "REQUEST_INSTALL_PACKAGES",
    "DELETE_PACKAGES", "REQUEST_DELETE_PACKAGES", "QUERY_ALL_PACKAGES",
    "READ_EXTERNAL_STORAGE", "WRITE_EXTERNAL_STORAGE",
    "MANAGE_EXTERNAL_STORAGE", "MOUNT_UNMOUNT_FILESYSTEMS",
    "ACCESS_FINE_LOCATION", "ACCESS_COARSE_LOCATION", "ACCESS_BACKGROUND_LOCATION",
    "CAMERA", "RECORD_AUDIO", "BODY_SENSORS",
    "GET_ACCOUNTS", "READ_CONTACTS", "WRITE_CONTACTS", "AUTHENTICATE_ACCOUNTS",
    "CHANGE_NETWORK_STATE", "CHANGE_WIFI_STATE", "BLUETOOTH_ADMIN", "NFC",
    "BIND_VPN_SERVICE", "CAPTURE_AUDIO_OUTPUT", "MODIFY_PHONE_STATE",
    "RECEIVE_BOOT_COMPLETED", "WAKE_LOCK", "DISABLE_KEYGUARD", "READ_LOGS",
    "FOREGROUND_SERVICE", "REQUEST_COMPANION_RUN_IN_BACKGROUND",
    "REQUEST_COMPANION_USE_DATA_IN_BACKGROUND",
])

# API/Sınıf isimlerini anlamsal kategorilere eşleyen kurallar
CATEGORY_RULES = {
    'sms': ('Landroid/telephony/SmsManager;', 'Landroid/telephony/SmsMessage;', 'Landroid/provider/Telephony$Sms;', 'sendTextMessage', 'sendMultipartTextMessage', 'getDefault()Landroid/telephony/SmsManager;'),
    'telephony': ('Landroid/telephony/TelephonyManager;', 'Lcom/android/internal/telephony/ITelephony;', 'Landroid/telephony/PhoneStateListener;', 'Landroid/telephony/SubscriptionManager;', 'getDeviceId', 'getLine1Number', 'getSimSerialNumber', 'getSubscriberId', 'getNetworkOperator', 'getCellLocation'),
    'crypto': ('Ljavax/crypto/Cipher;', 'Ljavax/crypto/spec/SecretKeySpec;', 'Ljavax/crypto/spec/IvParameterSpec;', 'Ljava/security/MessageDigest;', 'Ljava/security/KeyStore;', 'Ljavax/crypto/Mac;', 'Ljava/security/SecureRandom;', 'AES', 'DES', 'RSA', 'SHA-256', 'MD5', 'doFinal', 'getInstance'),
    'dynamic': ('Ldalvik/system/DexClassLoader;', 'Ldalvik/system/PathClassLoader;', 'Ldalvik/system/BaseDexClassLoader;', 'Ljava/lang/reflect/Method;', 'Ljava/lang/System;->loadLibrary', 'Ljava/lang/Runtime;->exec', 'Ljava/lang/ProcessBuilder;', 'loadClass', 'loadDex', '.dex', '.jar', '.apk'),
    'admin_operations': ('Landroid/app/admin/DevicePolicyManager;', 'Landroid/app/admin/DeviceAdminReceiver;', 'lockNow', 'wipeData', 'resetPassword', 'setPasswordQuality', 'removeActiveAdmin', 'isAdminActive'),
    'file_operations': ('Ljava/io/FileInputStream;', 'Ljava/io/FileOutputStream;', 'Ljava/io/File;', 'Ljava/io/RandomAccessFile;', 'openFileOutput', 'openFileInput', '/data/data/', '/sdcard/', '/mnt/', 'getExternalStorageDirectory', 'getFilesDir', 'deleteFile', 'mkdir', 'renameTo'),
    'location': ('Landroid/location/LocationManager;', 'Landroid/location/Location;', 'Landroid/location/LocationListener;', 'Lcom/google/android/gms/location/', 'requestLocationUpdates', 'getLastKnownLocation', 'getLatitude', 'getLongitude', 'GPS_PROVIDER', 'NETWORK_PROVIDER'),
    'media_capture': ('Landroid/hardware/Camera;', 'Landroid/hardware/camera2/', 'Landroid/media/MediaRecorder;', 'Landroid/media/AudioRecord;', 'takePicture', 'startRecording', 'setOutputFile', 'setAudioSource', 'setVideoSource'),
    'root_detection': ('/system/bin/su', '/system/xbin/su', 'busybox', 'magisk', 'Superuser.apk', 'eu.chainfire.supersu', 'com.noshufou.android.su', 'com.topjohnwu.magisk', 'test-keys', '/sbin/su'),
    'background_ops': ('Landroid/content/BroadcastReceiver;', 'Landroid/app/AlarmManager;', 'Landroid/app/Service;', 'Landroid/app/IntentService;', 'Landroid/app/job/JobScheduler;', 'Landroid/app/JobIntentService;', 'Landroidx/work/WorkManager;', 'setRepeating', 'setExact', 'onReceive', 'BOOT_COMPLETED'),
    'device_info': ('Landroid/os/Build;', 'Landroid/provider/Settings$Secure;', 'ANDROID_ID', 'getDeviceId', 'getSerialNumber', 'Build.MANUFACTURER', 'Build.MODEL', 'Build.VERSION', 'Build.FINGERPRINT', 'getSubscriberId', 'getMacAddress'),
    'network': ('Ljava/net/HttpURLConnection;', 'Ljava/net/URL;', 'Ljava/net/Socket;', 'Ljava/net/ServerSocket;', 'Lorg/apache/http/', 'Lokhttp3/', 'Landroid/net/ConnectivityManager;', 'Landroid/net/wifi/WifiManager;', 'Landroid/net/Uri;', 'openConnection', 'getInputStream', 'getOutputStream', 'setRequestMethod'),
    'reflection': ('Ljava/lang/Class;->forName', 'Ljava/lang/Class;->getDeclaredMethod', 'Ljava/lang/Class;->getMethod', 'Ljava/lang/reflect/Field;', 'Ljava/lang/reflect/Constructor;', 'invoke', 'setAccessible', 'newInstance', 'getDeclaredField'),
    'obfuscation': ('Landroid/util/Base64;', 'Base64.decode', 'Base64.encode', 'xor', 'unicode', '\\u0', 'Ljava/lang/String;->getBytes', 'Ljava/lang/String;->toCharArray'),
    'anti_debug': ('Landroid/os/Debug;->isDebuggerConnected', 'Landroid/os/Debug;->waitingForDebugger', '/proc/self/status', '/proc/self/maps', 'TracerPid', 'ptrace', 'JDWP'),
    'native_code': ('Ljava/lang/System;->loadLibrary', 'Ljava/lang/System;->load', '.so', 'lib/', 'arm64-v8a', 'armeabi-v7a', 'x86', 'native'),
    'privileged_ops': ('INSTALL_PACKAGES', 'DELETE_PACKAGES', 'READ_LOGS', 'MOUNT_UNMOUNT_FILESYSTEMS', 'WRITE_SECURE_SETTINGS', 'BIND_ACCESSIBILITY_SERVICE'),
    'banking_targets': ('paypal', 'wallet', 'banking', 'bank', 'mastercard', 'visa', 'finance', 'payment', 'transaction', 'account', 'balance', 'transfer'),
    'modern_libs': ('Landroidx/', 'Lcom/google/firebase/', 'Lcom/google/android/gms/', 'Lkotlin/', 'Lkotlinx/coroutines/', 'Lio/reactivex/', 'Lretrofit2/', 'Lcom/squareup/'),
    'accessibility': ('Landroid/accessibilityservice/AccessibilityService;', 'Landroid/view/accessibility/AccessibilityEvent;', 'Landroid/view/accessibility/AccessibilityNodeInfo;', 'onAccessibilityEvent', 'performGlobalAction', 'getRootInActiveWindow', 'findAccessibilityNodeInfosByText'),
    'notifications': ('Landroid/service/notification/NotificationListenerService;', 'Landroid/app/Notification;', 'Landroid/app/NotificationManager;', 'onNotificationPosted', 'getActiveNotifications', 'cancelNotification'),
    'webview': ('Landroid/webkit/WebView;', 'Landroid/webkit/WebViewClient;', 'Landroid/webkit/JavascriptInterface;', 'addJavascriptInterface', 'loadUrl', 'evaluateJavascript', 'setWebViewClient'),
    'overlay': ('Landroid/view/WindowManager;', 'Landroid/view/WindowManager$LayoutParams;', 'TYPE_SYSTEM_ALERT', 'TYPE_SYSTEM_OVERLAY', 'TYPE_APPLICATION_OVERLAY', 'addView', 'FLAG_NOT_FOCUSABLE'),
    'keylogging': ('Landroid/view/inputmethod/InputMethodService;', 'Landroid/inputmethodservice/Keyboard;', 'onKeyDown', 'onKeyUp', 'dispatchKeyEvent', 'setOnKeyListener'),
    'screenshot': ('Landroid/media/projection/MediaProjection;', 'Landroid/media/ImageReader;', 'Landroid/graphics/Bitmap;', 'getDrawingCache', 'createBitmap'),
    'clipboard': ('Landroid/content/ClipboardManager;', 'Landroid/content/ClipData;', 'getPrimaryClip', 'setPrimaryClip', 'addPrimaryClipChangedListener'),
    'contacts': ('Landroid/provider/ContactsContract;', 'Landroid/database/Cursor;', 'getContentResolver', 'query', 'CONTENT_URI', 'DISPLAY_NAME', 'PHONE_NUMBER'),
    'calendar': ('Landroid/provider/CalendarContract;', 'CalendarContract.Events', 'CalendarContract.Calendars'),
    'shell_exec': ('Ljava/lang/Runtime;->exec', 'Ljava/lang/ProcessBuilder;', 'su -c', 'sh', '/system/bin/sh', 'pm install', 'pm uninstall', 'am start'),
    'vpn': ('Landroid/net/VpnService;', 'Landroid/net/VpnService$Builder;', 'establish', 'protect', 'addAddress', 'addRoute'),
    'bluetooth': ('Landroid/bluetooth/BluetoothAdapter;', 'Landroid/bluetooth/BluetoothDevice;', 'Landroid/bluetooth/BluetoothSocket;', 'getDefaultAdapter', 'getBondedDevices', 'startDiscovery'),
    'nfc': ('Landroid/nfc/NfcAdapter;', 'Landroid/nfc/Tag;', 'getDefaultAdapter', 'enableForegroundDispatch'),
    'sensor': ('Landroid/hardware/SensorManager;', 'Landroid/hardware/Sensor;', 'getDefaultSensor', 'registerListener', 'TYPE_ACCELEROMETER', 'TYPE_GYROSCOPE'),
    'account': ('Landroid/accounts/AccountManager;', 'getAccounts', 'getAccountsByType', 'addAccountExplicitly', 'removeAccount'),
    'package_info': ('Landroid/content/pm/PackageManager;', 'Landroid/content/pm/ApplicationInfo;', 'getInstalledPackages', 'getInstalledApplications', 'getPackageInfo', 'queryIntentActivities'),
    'sqlite': ('Landroid/database/sqlite/SQLiteDatabase;', 'Landroid/database/sqlite/SQLiteOpenHelper;', 'execSQL', 'rawQuery', 'insert', 'update', 'delete'),
    'shared_prefs': ('Landroid/content/SharedPreferences;', 'getSharedPreferences', 'edit', 'putString', 'getString', 'commit', 'apply'),
    'content_provider': ('Landroid/content/ContentProvider;', 'Landroid/content/ContentResolver;', 'query', 'insert', 'update', 'delete', 'openFile'),
    'intent_hijacking': ('Landroid/content/Intent;', 'setComponent', 'getExtras', 'putExtra', 'startActivity', 'startService', 'sendBroadcast'),
    'classloader_manipulation': ('Ljava/lang/ClassLoader;', 'getSystemClassLoader', 'getParent', 'findClass', 'defineClass'),
    'hooking_frameworks': ('de.robv.android.xposed', 'XposedBridge', 'XposedHelpers', 'Lcom/elderdrivers/riru/edxp/', 'Lorg/lsposed/'),
    'emulator_detection': ('goldfish', 'ranchu', 'vbox', 'ttVM_', 'andy', 'nox', 'bluestacks', 'generic'),
}

# İzinleri anlamsal kategorilere eşle
PERM_TO_CATEGORY = {
    'READ_SMS': 'sms', 'SEND_SMS': 'sms', 'RECEIVE_SMS': 'sms', 'WRITE_SMS': 'sms',
    'READ_PHONE_STATE': 'telephony', 'CALL_PHONE': 'telephony', 'READ_CALL_LOG': 'telephony',
    'WRITE_CALL_LOG': 'telephony', 'ADD_VOICEMAIL': 'telephony', 'USE_SIP': 'telephony',
    'PROCESS_OUTGOING_CALLS': 'telephony', 'ANSWER_PHONE_CALLS': 'telephony',
    'READ_PHONE_NUMBERS': 'telephony',
    'BIND_DEVICE_ADMIN': 'admin_operations', 'DEVICE_ADMIN': 'admin_operations',
    'WRITE_SETTINGS': 'admin_operations', 'WRITE_SECURE_SETTINGS': 'admin_operations',
    'READ_EXTERNAL_STORAGE': 'file_operations', 'WRITE_EXTERNAL_STORAGE': 'file_operations',
    'MANAGE_EXTERNAL_STORAGE': 'file_operations', 'MOUNT_UNMOUNT_FILESYSTEMS': 'file_operations',
    'ACCESS_FINE_LOCATION': 'location', 'ACCESS_COARSE_LOCATION': 'location',
    'ACCESS_BACKGROUND_LOCATION': 'location',
    'CAMERA': 'media_capture', 'RECORD_AUDIO': 'media_capture', 'BODY_SENSORS': 'media_capture',
    'RECEIVE_BOOT_COMPLETED': 'background_ops', 'WAKE_LOCK': 'background_ops',
    'REQUEST_IGNORE_BATTERY_OPTIMIZATIONS': 'background_ops', 'FOREGROUND_SERVICE': 'background_ops',
    'REQUEST_COMPANION_RUN_IN_BACKGROUND': 'background_ops',
    'REQUEST_COMPANION_USE_DATA_IN_BACKGROUND': 'background_ops',
    'GET_ACCOUNTS': 'device_info', 'READ_CONTACTS': 'device_info', 'WRITE_CONTACTS': 'device_info',
    'AUTHENTICATE_ACCOUNTS': 'device_info',
    'SYSTEM_ALERT_WINDOW': 'overlay', 'DISABLE_KEYGUARD': 'overlay',
    'INSTALL_PACKAGES': 'privileged_ops', 'REQUEST_INSTALL_PACKAGES': 'privileged_ops',
    'DELETE_PACKAGES': 'privileged_ops', 'REQUEST_DELETE_PACKAGES': 'privileged_ops',
    'READ_LOGS': 'privileged_ops', 'QUERY_ALL_PACKAGES': 'privileged_ops',
    'BIND_ACCESSIBILITY_SERVICE': 'accessibility',
    'BIND_NOTIFICATION_LISTENER_SERVICE': 'notifications',
    'BIND_VPN_SERVICE': 'network', 'CHANGE_NETWORK_STATE': 'network',
    'CHANGE_WIFI_STATE': 'network', 'BLUETOOTH_ADMIN': 'network',
    'NFC': 'network',
    'CAPTURE_AUDIO_OUTPUT': 'media_capture', 'MODIFY_PHONE_STATE': 'telephony',
}

# Varlığı uygulamanın zararsız olma ihtimalini artıran izinler
BENIGN_HINT_PERMS = frozenset([
    "USE_FINGERPRINT", "USE_BIOMETRIC", "BLUETOOTH", "NFC",
    "VIBRATE", "FLASHLIGHT", "ACCESS_NOTIFICATION_POLICY",
    "SET_WALLPAPER", "SET_WALLPAPER_HINTS", "EXPAND_STATUS_BAR",
    "KILL_BACKGROUND_PROCESSES", "REORDER_TASKS",
    "GET_PACKAGE_SIZE", "CHANGE_WIFI_MULTICAST_STATE",
    "ACCESS_WIFI_STATE", "ACCESS_NETWORK_STATE", "INTERNET",
    "REQUEST_IGNORE_BATTERY_OPTIMIZATIONS", "FOREGROUND_SERVICE",
    "POST_NOTIFICATIONS", "SCHEDULE_EXACT_ALARM",
    "USE_FULL_SCREEN_INTENT", "REQUEST_COMPANION_PROFILE_WATCH",
    "REQUEST_OBSERVE_COMPANION_DEVICE_PRESENCE",
    "ACTIVITY_RECOGNITION", "READ_MEDIA_IMAGES", "READ_MEDIA_VIDEO",
    "READ_MEDIA_AUDIO", "ACCESS_MEDIA_LOCATION",
])


# Varlığı skoru düşürmesi gereken, yaygın ve güvenilir kütüphaneler
BENIGN_LIBRARIES = frozenset([
    'Landroidx/', 'Lcom/google/android/gms/', 'Lcom/google/firebase/',
    'Lokhttp3/', 'Lkotlin/', 'Lkotlinx/', 'Lcom/facebook/',
    'Lorg/json/', 'Lcom/google/gson/', 'Lcom/google/dagger/',
    'Lcom/squareup/retrofit2/', 'Lcom/squareup/picasso/', 'Lcom/squareup/okio/',
    'Lcom/squareup/moshi/', 'Lcom/squareup/leakcanary/',
    'Lcom/bumptech/glide/', 'Lio/reactivex/', 'Lorg/reactivestreams/',
    'Lcom/google/android/material/', 'Lcom/google/android/play/',
    'Lcom/google/common/', 'Lcom/google/protobuf/',
    'Lcom/airbnb/lottie/', 'Lcom/crashlytics/', 'Lio/fabric/',
    'Lorg/apache/commons/', 'Lorg/slf4j/', 'Lch/qos/logback/',
    'Lcom/jakewharton/', 'Lcom/android/volley/', 'Lcom/android/billingclient/',
    'Lcom/google/zxing/', 'Lcom/journeyapps/barcodescanner/',
    'Lde/hdodenhof/circleimageview/', 'Lcom/github/bumptech/',
    'Lcom/google/mlkit/', 'Lcom/google/ar/', 'Lcom/unity3d/',
    'Lcom/android/installreferrer/', 'Lcom/adjust/sdk/',
    'Lcom/appsflyer/', 'Lcom/mixpanel/android/', 'Lcom/amplitude/',
    'Lcom/segment/analytics/', 'Lcom/stripe/android/',
    'Lcom/paypal/android/', 'Lcom/braintreepayments/',
    'Lcom/twitter/sdk/', 'Lcom/linkedin/android/',
    'Lcom/microsoft/appcenter/', 'Lcom/amazonaws/',
    'Lio/grpc/', 'Lorg/greenrobot/eventbus/', 'Lcom/greenrobot/eventbus/',
    'Lcom/hannesdorfmann/mosby/', 'Lcom/arello_mobile/moxy/',
    'Lbutterknife/', 'Lcom/jakewharton/butterknife/',
    'Lcom/trello/rxlifecycle/', 'Lcom/uber/autodispose/',
    'Lcom/google/android/exoplayer2/', 'Lcom/google/android/datatransport/',
    'Lcom/android/support/', 'Landroid/support/v4/', 'Landroid/support/v7/',
    'Lcom/google/ads/', 'Lcom/google/android/ump/',
    'Lcom/facebook/ads/', 'Lcom/mopub/', 'Lcom/applovin/',
    'Lcom/unity3d/ads/', 'Lcom/vungle/', 'Lcom/chartboost/',
    'Lcom/inmobi/', 'Lcom/ironsource/', 'Lcom/tapjoy/',
])


# Anlamsal kategorilere atanan risk ağırlıkları
W = {
    "accessibility": 7.5,
    "overlay": 8,
    "notifications": 6.50,
    "dangerous_permissions": 12,
    "sms": 9.5,
    "admin_operations": 12.0,
    "dynamic": 10.5,
    "vpn": 10.5,
    "telephony": 9.8,
    "keylogging": 9.8,
    "root_detection": 9.5,
    "banking_targets": 6.5,
    "media_capture": 7.0,
    "screenshot": 7.5,
    "clipboard": 7.0,
    "webview": 7.5,
    "shell_exec": 5.5,
    "privileged_ops": 6.5,
    "hooking_frameworks": 6.5,
    "package_info": 6.0,
    "emulator_detection": 5.8,
    "contacts": 4,
    "device_info": 5.0,
    "account": 4.8,
    "classloader_manipulation": 5.5,
    "intent_hijacking": 5.5,
    "crypto": 4.0,
    "network": 4.5,
    "location": 4,
    "anti_debug": 4.5,
    "native_code": 4.0,
    "content_provider": 4.0,
    "background_ops": 4.0,
    "reflection": 4.0,
    "obfuscation": 4.0,
    "bluetooth": 4.0,
    "nfc": 3.8,
    "sensor": 3.5,
    "calendar": 3.2,
    "file_operations": 3.0,
    "sqlite": 2.5,
    "shared_prefs": 1.5,
    "modern_libs": 0,
}