# Analizden hariç tutulacak yaygın ve gürültüye neden olan sınıflar
STOP_CLASSES = frozenset([
    "Ljava/lang/Object;", "Ljava/lang/String;", "Ljava/lang/StringBuilder;",
    "Ljava/lang/StringBuffer;", "Ljava/lang/Class;", "Ljava/lang/System;",
    "Ljava/util/ArrayList;", "Ljava/util/List;", "Ljava/util/Map;",
    "Ljava/util/HashMap;", "Ljava/util/HashSet;", "Ljava/util/Set;",
    "Ljava/util/Iterator;", "Ljava/util/Collection;", "Ljava/util/Arrays;",
    "Ljava/util/Collections;", "Ljava/util/Date;", "Ljava/util/Calendar;",
    "Ljava/lang/Exception;", "Ljava/lang/Throwable;", "Ljava/lang/Error;",
    "Ljava/lang/RuntimeException;", "Ljava/lang/Integer;", "Ljava/lang/Long;",
    "Ljava/lang/Float;", "Ljava/lang/Double;", "Ljava/lang/Boolean;",
    "Ljava/lang/Byte;", "Ljava/lang/Short;", "Ljava/lang/Character;",
    "Ljava/lang/Number;", "Ljava/lang/Math;", "Ljava/lang/Thread;",
    "Ljava/lang/Runnable;", "Ljava/io/Serializable;", "Ljava/io/IOException;",
    "Ljava/io/InputStream;", "Ljava/io/OutputStream;", "Ljava/io/Reader;",
    "Ljava/io/Writer;", "Ljava/io/BufferedReader;", "Ljava/io/BufferedWriter;",
    "Ljava/io/PrintWriter;", "Ljava/io/Closeable;",
    "Ljava/lang/annotation/Annotation;", "Ljava/lang/Enum;",
    "Ljava/text/SimpleDateFormat;", "Ljava/text/DateFormat;",
    "Landroid/os/Bundle;", "Landroid/os/Parcel;", "Landroid/os/Parcelable;",
    "Landroid/os/Handler;", "Landroid/os/Message;", "Landroid/os/Looper;",
    "Landroid/content/Context;", "Landroid/content/res/Resources;",
    "Landroid/content/res/Configuration;", "Landroid/util/Log;",
    "Landroid/util/DisplayMetrics;", "Landroid/util/TypedValue;",
    "Landroid/view/View;", "Landroid/view/ViewGroup;", "Landroid/view/LayoutInflater;",
    "Landroid/widget/TextView;", "Landroid/widget/Button;", "Landroid/widget/EditText;",
    "Landroid/widget/ImageView;", "Landroid/widget/LinearLayout;",
    "Landroid/widget/RelativeLayout;", "Landroid/widget/FrameLayout;",
    "Landroid/widget/Toast;", "Landroid/app/Activity;", "Landroid/app/Fragment;",
    "Landroid/app/Application;", "Landroid/app/Dialog;",
    "Landroidx/appcompat/app/AppCompatActivity;",
    "Landroidx/fragment/app/Fragment;", "Landroidx/fragment/app/FragmentActivity;",
    "Landroidx/recyclerview/widget/RecyclerView;",
    "Landroidx/viewpager/widget/ViewPager;",
    "Landroid/support/v7/app/AppCompatActivity;",
    "Landroid/support/v4/app/Fragment;", "Landroid/support/v4/app/FragmentActivity;",
    "Lcom/google/android/material/", "Landroidx/constraintlayout/",
    "Landroidx/lifecycle/", "Landroidx/core/",
    "Lcom/google/gson/", "Lorg/json/JSONObject;", "Lorg/json/JSONArray;",
    "Ljava/util/concurrent/", "Ljava/util/regex/Pattern;",
    "Landroid/graphics/Bitmap;", "Landroid/graphics/Canvas;",
    "Landroid/graphics/Paint;", "Landroid/graphics/Color;",
    "Landroid/graphics/drawable/Drawable;", "Landroid/text/TextUtils;",
    "Landroid/view/MotionEvent;", "Landroid/view/KeyEvent;",
    "Landroid/view/ViewTreeObserver;", "Landroid/animation/",
    "Lkotlin/jvm/internal/", "Lkotlin/Metadata;",
])

# Yüksek riskli ve doğrudan skoru etkileyen tehlikeli izinler
DANGEROUS_PERMISSIONS = frozenset([
    "SEND_SMS", "READ_SMS", "RECEIVE_SMS", "WRITE_SMS",
    "READ_PHONE_STATE", "CALL_PHONE", "READ_CALL_LOG", "WRITE_CALL_LOG",
    "ADD_VOICEMAIL", "USE_SIP", "PROCESS_OUTGOING_CALLS",
    "ANSWER_PHONE_CALLS", "READ_PHONE_NUMBERS",
    "BIND_DEVICE_ADMIN", "SYSTEM_ALERT_WINDOW",
    "BIND_ACCESSIBILITY_SERVICE", "BIND_NOTIFICATION_LISTENER_SERVICE",
    "REQUEST_IGNORE_BATTERY_OPTIMIZATIONS", "WRITE_SETTINGS", "WRITE_SECURE_SETTINGS",
    "INSTALL_PACKAGES", "REQUEST_INSTALL_PACKAGES",
    "DELETE_PACKAGES", "REQUEST_DELETE_PACKAGES", "QUERY_ALL_PACKAGES",
    "READ_EXTERNAL_STORAGE", "WRITE_EXTERNAL_STORAGE",
    "MANAGE_EXTERNAL_STORAGE", "MOUNT_UNMOUNT_FILESYSTEMS",
    "ACCESS_FINE_LOCATION", "ACCESS_COARSE_LOCATION", "ACCESS_BACKGROUND_LOCATION",
    "CAMERA", "RECORD_AUDIO", "BODY_SENSORS",
    "GET_ACCOUNTS", "READ_CONTACTS", "WRITE_CONTACTS", "AUTHENTICATE_ACCOUNTS",
    "CHANGE_NETWORK_STATE", "CHANGE_WIFI_STATE", "BLUETOOTH_ADMIN", "NFC",
    "BIND_VPN_SERVICE", "CAPTURE_AUDIO_OUTPUT", "MODIFY_PHONE_STATE",
    "RECEIVE_BOOT_COMPLETED", "WAKE_LOCK", "DISABLE_KEYGUARD", "READ_LOGS",
    "FOREGROUND_SERVICE", "REQUEST_COMPANION_RUN_IN_BACKGROUND",
    "REQUEST_COMPANION_USE_DATA_IN_BACKGROUND",
])

# API/Sınıf isimlerini anlamsal kategorilere eşleyen kurallar
CATEGORY_RULES = {
'benign_ui': (
    'Landroid/widget/',
    'Landroidx/recyclerview/widget/RecyclerView',
    'Landroidx/viewpager/widget/ViewPager',
    'Landroidx/appcompat/widget/Toolbar',
    'Lcom/google/android/material/',
    'Landroidx/constraintlayout/',
    'Landroid/view/Menu',
    'Landroid/widget/ImageView',
    'Landroid/widget/TextView',
    'onClick',
    'setContentView',
    'Landroidx/activity/ComponentActivity',
        'Landroidx/appcompat/app/ActionBar',
        'onCreate', 'onStart', 'onResume', 'onPause', 'onStop', 'onDestroy',
),
'sms': (
'Landroid/telephony/SmsManager;',
'Landroid/telephony/SmsMessage;',
'Landroid/provider/Telephony$Sms;',
'sendTextMessage',
'sendMultipartTextMessage',
'getDefault()Landroid/telephony/SmsManager;',
'sendDataMessage',
'sendTextMessageWithoutPersisting',
'Landroid/provider/Telephony$Mms;',
'SmsManager.sendMultipartTextMessage',
'SmsManager.injectSmsPdu',
'Landroid/telephony/SmsManager;->injectSmsPdu',
'createAppSpecificSmsToken',
'sendMultimediaMessage',
'Landroid/telephony/SmsManager;->createAppSpecificSmsToken',
),
'telephony': (
'Landroid/telephony/TelephonyManager;',
'Lcom/android/internal/telephony/ITelephony;',
'Landroid/telephony/PhoneStateListener;',
'Landroid/telephony/SubscriptionManager;',
'getDeviceId',
'getLine1Number',
'getSimSerialNumber',
'getSubscriberId',
'getNetworkOperator',
'getCellLocation',
'getSimOperatorName',
'getNetworkCountryIso',
'getCallState',
'getDataState',
'getNetworkType',
'listen(Landroid/telephony/PhoneStateListener;)',
'getAllCellInfo',
'getNeighboringCellInfo',
'getServiceState',
'getSimCountryIso',
'Landroid/telephony/TelephonyManager;->getAllCellInfo',
'endCall',
),
'crypto': (
'Ljavax/crypto/Cipher;',
'Ljavax/crypto/spec/SecretKeySpec;',
'Ljavax/crypto/spec/IvParameterSpec;',
'Ljava/security/MessageDigest;',
'Ljava/security/KeyStore;',
'Ljavax/crypto/Mac;',
'Ljava/security/SecureRandom;',
'AES',
'DES',
'RSA',
'SHA-256',
'MD5',
'doFinal',
'getInstance',
'CipherInputStream',
'CipherOutputStream',
'KeyGenerator',
'generateKey',
'PBEKeySpec',
'SecretKeyFactory',
'KeyAgreement',
'KeyPairGenerator',
'Ljavax/crypto/CipherInputStream;',
'Ljavax/crypto/CipherOutputStream;',
'init',
'update',
'Ljavax/crypto/KeyAgreement;',
'generateSecret',
'SHA-1',
'ECDH',
'javax/crypto/SecretKey',
'javax/crypto/SecretKeyFactory',
'javax/crypto/CipherOutputStream',
'javax/crypto/CipherInputStream',
),
'dynamic': (
'Ldalvik/system/DexClassLoader;',
'Ldalvik/system/PathClassLoader;',
'Ldalvik/system/BaseDexClassLoader;',
'Ljava/lang/reflect/Method;',
'Ljava/lang/System;->loadLibrary',
'Ljava/lang/Runtime;->exec',
'Ljava/lang/ProcessBuilder;',
'loadClass',
'loadDex',
'.dex',
'.jar',
'.apk',
'createPackageContext',
'getClassLoader',
'BaseDexClassLoader.defineClass',
'DexFile.loadDex',
'defineClass',
'definePackage',
'Ldalvik/system/DexFile;',
'optimize',
'loadDexFile',
'getDexClassLoader',
'defineClassN',
'Ljava/lang/Class;->forName',  # reflection-related loadClass patterns
'Ljava/lang/Runtime;->exec',
'Ljava/lang/Class;->forName',
    'Ljava/lang/Runtime;->exec',
    'invoke',
    'dalvik.system.VMStack',
),
'admin_operations': (
'Landroid/app/admin/DevicePolicyManager;',
'Landroid/app/admin/DeviceAdminReceiver;',
'lockNow',
'wipeData',
'resetPassword',
'setPasswordQuality',
'removeActiveAdmin',
'isAdminActive',
'setCameraDisabled',
'setKeyguardDisabled',
'setScreenCaptureDisabled',
'addUserRestriction',
'setLockTaskPackages',
'setGlobalProxy',
'setMaximumTimeToLock',
'setPasswordMinimumLength',
'getPasswordQuality',
'Landroid/app/admin/DevicePolicyManager;->setGlobalProxy',
),
'file_operations': (
'Ljava/io/FileInputStream;',
'Ljava/io/FileOutputStream;',
'Ljava/io/File;',
'Ljava/io/RandomAccessFile;',
'openFileOutput',
'openFileInput',
'/data/data/',
'/sdcard/',
'/mnt/',
'getExternalStorageDirectory',
'getFilesDir',
'deleteFile',
'mkdir',
'renameTo',
'Environment.getExternalStoragePublicDirectory',
'listFiles',
'FileChannel',
'FileWriter',
'FileReader',
'FileProvider',
'.nomedia',
'getCanonicalPath',
'createNewFile',
'setReadable',
'setWritable',
'Ljava/io/File;->createNewFile',
'getExternalFilesDir',
),
'location': (
'Landroid/location/LocationManager;',
'Landroid/location/Location;',
'Landroid/location/LocationListener;',
'Lcom/google/android/gms/location/',
'requestLocationUpdates',
'getLastKnownLocation',
'getLatitude',
'getLongitude',
'GPS_PROVIDER',
'NETWORK_PROVIDER',
'addGpsStatusListener',
'getBestProvider',
'isProviderEnabled',
'LocationServices',
'Lcom/google/android/gms/location/LocationServices;',
'Lcom/google/android/gms/location/FusedLocationProviderClient;',
        'FusedLocationProviderClient',
        'getLastLocation',
),
'camera_capture': (
    'Landroid/hardware/Camera;',
    'Landroid/hardware/camera2/',
    'takePicture',
    'setPreviewDisplay',
    'Landroid/hardware/Camera;->setPreviewCallback',
    # İzinlerden 'CAMERA'yı da buraya ekleyebiliriz (gerçi PERM_TO_CATEGORY'de var)
),
# YENİ KATEGORİ 2: Sadece Mikrofon/Ses
'microphone_capture': (
    'Landroid/media/MediaRecorder;',
    'Landroid/media/AudioRecord;',
    'startRecording',
    'setAudioSource',
    'setOutputFile',
    'prepare',
    'Landroid/media/MediaRecorder;->prepare',
    # İzinlerden 'RECORD_AUDIO'yu da buraya ekleyebiliriz
),
'root_detection': (
'/system/bin/su',
'/system/xbin/su',
'busybox',
'magisk',
'Superuser.apk',
'eu.chainfire.supersu',
'com.noshufou.android.su',
'com.topjohnwu.magisk',
'test-keys',
'/sbin/su',
'/system/bin/which su',
'com.koushikdutta.superuser',
'com.thirdparty.superuser',
'checkRootMethod',
'/data/local/xbin/su',
),
'background_ops': (
'Landroid/content/BroadcastReceiver;',
'Landroid/app/AlarmManager;',
'Landroid/app/Service;',
'Landroid/app/IntentService;',
'Landroid/app/job/JobScheduler;',
'Landroid/app/JobIntentService;',
'Landroidx/work/WorkManager;',
'setRepeating',
'setExact',
'onReceive',
'BOOT_COMPLETED',
'setInexactRepeating',
'cancel',
'onHandleWork',
'enqueueUniquePeriodicWork',
'Landroidx/work/WorkManager;->enqueueUniquePeriodicWork',
'Landroid/os/PowerManager$WakeLock;->acquire',
),
'device_info': (
'Landroid/os/Build;',
'Landroid/provider/Settings$Secure;',
'ANDROID_ID',
'getDeviceId',
'getSerialNumber',
'Build.MANUFACTURER',
'Build.MODEL',
'Build.VERSION',
'Build.FINGERPRINT',
'getSubscriberId',
'getMacAddress',
'Build.BOARD',
'Build.BOOTLOADER',
'Build.HARDWARE',
'getRadioVersion',
'getNetworkOperatorName',
),
'network': (
'Ljava/net/HttpURLConnection;',
'Ljava/net/URL;',
'Ljava/net/Socket;',
'Ljava/net/ServerSocket;',
'Lorg/apache/http/',
'Lokhttp3/',
'Landroid/net/ConnectivityManager;',
'Landroid/net/wifi/WifiManager;',
'Landroid/net/Uri;',
'openConnection',
'getInputStream',
'getOutputStream',
'setRequestMethod',
'SocketChannel',
'DatagramSocket',
'HttpClient',
'HttpsURLConnection',
'URLConnection.connect',
'SSLSocketFactory',
'TrustManager',
'HostnameVerifier',
'InetAddress.getByName',
'setDoOutput',
'setDoInput',
'setRequestProperty',
'connect',
'disconnect',
'Lokhttp3/Request$Builder;',
'POST',
'GET',
'User-Agent',
'Lokhttp3/OkHttpClient;',         # ekleme
'Lokhttp3/Request;',              # ekleme
'Lokhttp3/Response;',             # ekleme
'Lokhttp3/Interceptor;',          # ekleme
'Lretrofit2/Retrofit;',           # ekleme
'Lretrofit2/Call;',               # ekleme
'Lcom/android/volley/',                    # Volley networking
    'Lio/ktor/client/',                        # Ktor client
    'Landroidx/work/NetworkType',              # WorkManager network conditions
    'Lcom/github/nkzawa/socketio/',            # Socket.IO client
    'Lio/socket/client/Socket',                # Socket.IO
    'Lcom/squareup/okhttp3/websocket/',
    'Lcom/squareup/okhttp3/websocket/',
    'Lio/socket/client/Socket', 
    'Lorg/eclipse/paho/client/mqttv3/',
    'Ljava/net/Socket;->connect',  
),
'reflection': (
'Ljava/lang/Class;->forName',
'Ljava/lang/Class;->getDeclaredMethod',
'Ljava/lang/Class;->getMethod',
'Ljava/lang/reflect/Field;',
'Ljava/lang/reflect/Constructor;',
'invoke',
'setAccessible',
'newInstance',
'getDeclaredField',
'invokeExact',
'getDeclaredMethods',
'getDeclaredFields',
'Proxy.newProxyInstance',
'getConstructors',
'getDeclaredConstructors',
'Ljava/lang/reflect/Proxy;',
'newProxyInstance',
'Ljava/lang/Class;->getConstructors',
),
'obfuscation': (
'Landroid/util/Base64;',
'Base64.decode',
'Base64.encode',
'xor',
'unicode',
'\\u0',
'Ljava/lang/String;->getBytes',
'Ljava/lang/String;->toCharArray',
'Base64InputStream',
'StringBuilder.reverse',
'StringBuffer.reverse',
'URLEncoder.encode',
'InflaterInputStream',
'GZIPInputStream',
'AES/CBC/PKCS5Padding',
'rot13',
'hexEncode',
'decryptString',
'encryptString',
'Ljava/util/zip/InflaterInputStream;',
'control flow obfuscation',
),
'anti_debug': (
'Landroid/os/Debug;->isDebuggerConnected',
'Landroid/os/Debug;->waitingForDebugger',
'/proc/self/status',
'/proc/self/maps',
'TracerPid',
'ptrace',
'JDWP',
'android.os.Debug.waitingForDebugger',
'System.getenv("ro.debuggable")',
'SystemProperties.get("ro.build.type")',
'isEmulator',
'Build.TAGS.contains("test-keys")',
'android.os.SystemProperties.get',
'ro.debuggable',
'ro.secure',
'killProcess',
'exit',
'Landroid/os/Process;->myPid',
),
'native_code': (
'Ljava/lang/System;->loadLibrary',
'Ljava/lang/System;->load',
'.so',
'lib/',
'arm64-v8a',
'armeabi-v7a',
'x86',
'native',
'JNIEXPORT',
'JNIEnv',
'jstring',
'libart.so',
'nativeMethod',
),
'privileged_ops': (
'INSTALL_PACKAGES',
'DELETE_PACKAGES',
'READ_LOGS',
'MOUNT_UNMOUNT_FILESYSTEMS',
'WRITE_SECURE_SETTINGS',
'BIND_ACCESSIBILITY_SERVICE',
'CHANGE_CONFIGURATION',
'SYSTEM_ALERT_WINDOW',
'READ_FRAME_BUFFER',
'INJECT_EVENTS',
),
'banking_targets': (
'paypal',
'wallet',
'banking',
'bank',
'mastercard',
'visa',
'finance',
'payment',
'transaction',
'account',
'balance',
'transfer',
'iban',
'otp',
'pin',
'credentials',
'token',
'2fa',
'secureid',
'swift',
'credit card',
'debit card',
'cvv',
'expiration date',
'bitcoin wallet',
'cryptocurrency',
),
'modern_libs': (
'Landroidx/',
'Lcom/google/firebase/',
'Lcom/google/android/gms/',
'Lkotlin/',
'Lkotlinx/coroutines/',
'Lio/reactivex/',
'Lretrofit2/',
'Lcom/squareup/',
'Lcom/google/dagger/',
'Lcom/google/gson/',
'Lio/realm/',
'Lcom/airbnb/lottie/',
'Lcom/google/firebase/messaging/',
        'Lcom/google/firebase/analytics/',
        'Lcom/google/firebase/installations/',
        'Lcom/google/android/exoplayer2/',
        'Lcom/squareup/okhttp3/',
        'Lcom/squareup/retrofit2/',
        'Lcom/google/android/play/core/',          # App Bundle/Dynamic Features
    'Lcom/google/android/play/core/splitinstall/',
    'Lcom/google/android/play/core/review/',   # In-App Reviews
    'Lcom/google/android/play/core/appupdate/', # In-App Updates
    'Landroidx/biometric/',                    # Biometric auth
    'Landroidx/camera/core/',                  # CameraX
    'Landroidx/room/',                         # Room Database
    'Landroidx/navigation/',                   # Navigation component
    'Landroidx/paging/',                       # Paging library
    'Landroidx/security/crypto/',
    'Landroidx/security/crypto/',
    'Landroidx/compose/ui/', 
    'Lcom/google/mlkit/', 
    'Lcom/google/ar/core/',
    'Lio/ktor/', 
    'Lorg/koin/',
    'Lio/coil-kt/',
),
'accessibility': (
'Landroid/accessibilityservice/AccessibilityService;',
'Landroid/view/accessibility/AccessibilityEvent;',
'Landroid/view/accessibility/AccessibilityNodeInfo;',
'onAccessibilityEvent',
'performGlobalAction',
'getRootInActiveWindow',
'findAccessibilityNodeInfosByText',
'performAction',
'getText',
'findFocus',
'getWindow',
'TYPE_VIEW_CLICKED',
'TYPE_VIEW_TEXT_CHANGED',
'dispatchGesture',
'AccessibilityNodeInfo.ACTION_CLICK',
'getSource',
'recycle',
'Landroid/view/accessibility/AccessibilityNodeInfo;->recycle',
),
'notifications': (
'Landroid/service/notification/NotificationListenerService;',
'Landroid/app/Notification;',
'Landroid/app/NotificationManager;',
'onNotificationPosted',
'getActiveNotifications',
'cancelNotification',
'NotificationChannel',
'createNotificationChannel',
'deleteNotificationChannel',
'Landroid/app/NotificationManager;->createNotificationChannel',
'Landroidx/core/app/NotificationCompat;',
        'Landroidx/core/app/NotificationManagerCompat;',
        'NotificationCompat',
),
'webview': (
'Landroid/webkit/WebView;',
'Landroid/webkit/WebViewClient;',
'Landroid/webkit/JavascriptInterface;',
'addJavascriptInterface',
'loadUrl',
'evaluateJavascript',
'setWebViewClient',
'setWebChromeClient',
'shouldOverrideUrlLoading',
'loadDataWithBaseURL',
'setJavaScriptEnabled',
'postUrl',
'onPageFinished',
'onReceivedError',
'shouldInterceptRequest',
'Landroid/webkit/WebResourceRequest;',
'Landroid/webkit/WebSettings;',
        'setJavaScriptEnabled',
        'addJavascriptInterface'
),
'overlay': (
'Landroid/view/WindowManager;',
'Landroid/view/WindowManager$LayoutParams;',
'TYPE_SYSTEM_ALERT',
'TYPE_SYSTEM_OVERLAY',
'TYPE_APPLICATION_OVERLAY',
'addView',
'FLAG_NOT_FOCUSABLE',
'TYPE_ACCESSIBILITY_OVERLAY',
'updateViewLayout',
'removeView',
'FLAG_NOT_TOUCH_MODAL',
),
'keylogging': (
'Landroid/view/inputmethod/InputMethodService;',
'Landroid/inputmethodservice/Keyboard;',
'onKeyDown',
'onKeyUp',
'dispatchKeyEvent',
'setOnKeyListener',
'KeyEvent',
'getKeyCode',
'getCharacters',
'Landroid/view/KeyEvent;',
),
'screenshot': (
'Landroid/media/projection/MediaProjection;',
'Landroid/media/ImageReader;',
'Landroid/graphics/Bitmap;',
'getDrawingCache',
'createBitmap',
'createVirtualDisplay',
'acquireLatestImage',
'setSecure',
'Landroid/media/projection/MediaProjection;->createVirtualDisplay',
),
'clipboard': (
'Landroid/content/ClipboardManager;',
'Landroid/content/ClipData;',
'getPrimaryClip',
'setPrimaryClip',
'addPrimaryClipChangedListener',
'getText',
'hasText',
'getItemAt',
'Landroid/content/ClipData;->getItemAt',
),
'contacts': (
'Landroid/provider/ContactsContract;',
'Landroid/database/Cursor;',
'getContentResolver',
'query',
'CONTENT_URI',
'DISPLAY_NAME',
'PHONE_NUMBER',
'ContactsContract.CommonDataKinds.Email',
'ContactsContract.CommonDataKinds.Phone',
'insert',
'update',
),
'calendar': (
'Landroid/provider/CalendarContract;',
'CalendarContract.Events',
'CalendarContract.Calendars',
'CalendarContract.Reminders',
'CalendarContract.Attendees',
'queryEvents',
'insertEvent',
),
'shell_exec': (
'Ljava/lang/Runtime;->exec',
'Ljava/lang/ProcessBuilder;',
'su -c',
'sh',
'/system/bin/sh',
'pm install',
'pm uninstall',
'am start',
'getRuntime',
'process.waitFor',
'inputStream',
'outputStream',
'adb',
),
'vpn': (
'Landroid/net/VpnService;',
'Landroid/net/VpnService$Builder;',
'establish',
'protect',
'addAddress',
'addRoute',
'addDnsServer',
'setMtu',
'setUnderlyingNetworks',
'Landroid/net/VpnService$Builder;->addDnsServer',
),
'bluetooth': (
'Landroid/bluetooth/BluetoothAdapter;',
'Landroid/bluetooth/BluetoothDevice;',
'Landroid/bluetooth/BluetoothSocket;',
'getDefaultAdapter',
'getBondedDevices',
'startDiscovery',
'enable',
'disable',
'getRemoteDevice',
'createRfcommSocketToServiceRecord',
),
'nfc': (
'Landroid/nfc/NfcAdapter;',
'Landroid/nfc/Tag;',
'getDefaultAdapter',
'enableForegroundDispatch',
'disableForegroundDispatch',
'isEnabled',
'NdefMessage',
'Landroid/nfc/NdefMessage;',
),
'sensor': (
'Landroid/hardware/SensorManager;',
'Landroid/hardware/Sensor;',
'getDefaultSensor',
'registerListener',
'TYPE_ACCELEROMETER',
'TYPE_GYROSCOPE',
'TYPE_PROXIMITY',
'TYPE_LIGHT',
'SensorEvent',
'unregisterListener',
),
'account': (
'Landroid/accounts/AccountManager;',
'getAccounts',
'getAccountsByType',
'addAccountExplicitly',
'removeAccount',
'getPassword',
'getUserData',
'setAuthToken',
'blockingGetAuthToken',
),
'package_info': (
'Landroid/content/pm/PackageManager;',
'Landroid/content/pm/ApplicationInfo;',
'getInstalledPackages',
'getInstalledApplications',
'getPackageInfo',
'queryIntentActivities',
'getLaunchIntentForPackage',
'getPermissionInfo',
'checkPermission',
'Landroid/content/pm/PackageManager;->checkPermission',
),
'sqlite': (
'Landroid/database/sqlite/SQLiteDatabase;',
'Landroid/database/sqlite/SQLiteOpenHelper;',
'execSQL',
'rawQuery',
'insert',
'update',
'delete',
'setTransactionSuccessful',
'inTransaction',
'SQLiteStatement',
'execute',
'Landroidx/room/Database;',                # Room Database
    'Landroidx/room/Dao;',
    'Landroidx/room/Entity;',
    'Landroidx/room/Query;',
    'Lio/realm/RealmObject;',                  # Realm Database
    'Lio/objectbox/Box;',
    'Lio/realm/RealmObject;',
    'Lio/objectbox/Box;',
    'Landroidx/room/RoomDatabase;',
),
'analytics': (                                 # Yeni kategori
    'Lcom/google/firebase/analytics/',
    'Lcom/google/android/gms/analytics/',
    'Lcom/flurry/android/',
    'Lcom/mixpanel/android/',
    'Lcom/amplitude/api/',
    'Lcom/crashlytics/android/Crashlytics;',
    'Lcom/google/firebase/crashlytics/',
    'Lcom/microsoft/appcenter/analytics/',
    'Lcom/segment/analytics/',
    'Lcom/newrelic/agent/android/',
    'Lcom/datadog/android/',
),
'shared_prefs': (
'Landroid/content/SharedPreferences;',
'getSharedPreferences',
'edit',
'putString',
'getString',
'commit',
'apply',
'putBoolean',
'getBoolean',
'clear',
'remove',
),
'content_provider': (
'Landroid/content/ContentProvider;',
'Landroid/content/ContentResolver;',
'query',
'insert',
'update',
'delete',
'openFile',
'getType',
'bulkInsert',
'notifyChange',
'registerContentObserver',
),
'intent_hijacking': (
'Landroid/content/Intent;',
'setComponent',
'getExtras',
'putExtra',
'startActivity',
'startService',
'sendBroadcast',
'addCategory',
'setData',
'setType',
'Intent.FLAG_GRANT_READ_URI_PERMISSION',
),
'classloader_manipulation': (
'Ljava/lang/ClassLoader;',
'getSystemClassLoader',
'getParent',
'findClass',
'defineClass',
'loadClass',
'getResource',
'findResource',
'Ljava/lang/ClassLoader;->loadClass',
),
'hooking_frameworks': (
'de.robv.android.xposed',
'XposedBridge',
'XposedHelpers',
'Lcom/elderdrivers/riru/edxp/',
'Lorg/lsposed/',
'frida',
'substrate',
'cydia',
'hook',
'methodHook',
'XC_MethodHook',
'findAndHookMethod',
'beforeHookedMethod',
'afterHookedMethod',
'com.saurik.substrate',
),
'emulator_detection': (
'goldfish',
'ranchu',
'vbox',
'ttVM_',
'andy',
'nox',
'bluestacks',
'generic',
'qemu',
'/proc/cpuinfo',
'Build.FINGERPRINT',
'Build.MODEL',
'Build.PRODUCT sdk_google_phone_armv7',
'Build.HARDWARE ranchu',
'emulator-5554',
'000000000000000',
),
'exfiltration': (
'MultipartEntityBuilder',
'DataOutputStream.write',
'OutputStreamWriter',
'FileInputStream.read',
'upload',
'postData',
'writeBytes',
'DataOutputStream.flush',
'setChunkedStreamingMode',
'multipart/form-data',
'base64Encode',
'compress',
'Lokhttp3/MultipartBody;',
),
'persistence': (
'RECEIVE_BOOT_COMPLETED',
'ACTION_BOOT_COMPLETED',
'AlarmManager.setRepeating',
'JobScheduler.schedule',
'BroadcastReceiver.onReceive',
'Service.onStartCommand',
'android.intent.action.BATTERY_CHANGED',
'android.intent.action.PACKAGE_ADDED',
'setExactAndAllowWhileIdle',
'ignoreBatteryOptimization',
),
'ui_injection': (
'LayoutInflater.inflate',
'WindowManager.addView',
'setContentView',
'AlertDialog.Builder',
'Toast.makeText',
'TYPE_APPLICATION_OVERLAY',
'ViewGroup.addView',
'setVisibility',
'bringToFront',
'phishing overlay',
),
'data_theft': (
'getContentResolver.query',
'ContactsContract.CommonDataKinds.Email',
'CallLog.Calls',
'SmsMessage.getMessageBody',
'FileInputStream',
'Browser.BOOKMARKS_URI',
'Telephony.Mms.CONTENT_URI',
'getInputStream',
'readBytes',
),
'anti_vm': (
'qemu',
'goldfish',
'ranchu',
'/proc/cpuinfo',
'Build.FINGERPRINT',
'Build.MODEL',
'Build.DEVICE generic',
'Build.USER android-build',
'ro.hardware qemu',
'init.svc.qemu-props',
),
'c2_communication': (
'beacon',
'heartbeat',
'command and control',
'C2',
'pollServer',
'registerDevice',
'sendCommand',
'http beacon',
),
'adware': (
'AdMob',
'AdView',
'loadAd',
'showInterstitial',
'Lcom/google/android/gms/ads/',
'ad click',
'impression',
),
'ransomware': (
'encryptFile',
'decryptFile',
'ransom note',
'pay bitcoin',
'file locked',
'your files are encrypted',
'your files are encrypted',
    'README_FOR_DECRYPT.txt', 
    '.locked',
    '.encrypted',
    'AES/CBC/PKCS5Padding',
),
'spyware': (
'trackUser',
'monitorActivity',
'sendLocation',
'logCalls',
'keylogger',
'screen record',
'logCalls',
    'keylogger',
    'screen record',
    'whatsapp/Databases', 
    'com.facebook.katana', 
    'com.facebook.orca',
    'getRunningAppProcesses',
),
'permission_abuse': (
'requestPermissions',
'onRequestPermissionsResult',
'dangerous permission',
'READ_SMS',
'WRITE_EXTERNAL_STORAGE',
'Landroid/app/Activity;->requestPermissions',
),
'payment_sdk': (
    'Lcom/stripe/android/',
    'Lcom/paypal/android/',
    'Lcom/braintreepayments/api/',
    'Lcom/adyen/checkout/',
    'com/google/android/gms/wallet/',
),
'permissions': (
    'Landroidx/core/app/ActivityCompat;',
    'Landroidx/core/content/ContextCompat;',
    'checkSelfPermission',
    'requestPermissions',
    'shouldShowRequestPermissionRationale',
    'onRequestPermissionsResult',
),
}

# İzinleri anlamsal kategorilere eşle
PERM_TO_CATEGORY = {
    'READ_SMS': 'sms', 'SEND_SMS': 'sms', 'RECEIVE_SMS': 'sms', 'WRITE_SMS': 'sms',
    'READ_PHONE_STATE': 'telephony', 'CALL_PHONE': 'telephony', 'READ_CALL_LOG': 'telephony',
    'WRITE_CALL_LOG': 'telephony', 'ADD_VOICEMAIL': 'telephony', 'USE_SIP': 'telephony',
    'PROCESS_OUTGOING_CALLS': 'telephony', 'ANSWER_PHONE_CALLS': 'telephony',
    'READ_PHONE_NUMBERS': 'telephony',
    'BIND_DEVICE_ADMIN': 'admin_operations', 'DEVICE_ADMIN': 'admin_operations',
    'WRITE_SETTINGS': 'admin_operations', 'WRITE_SECURE_SETTINGS': 'admin_operations',
    'READ_EXTERNAL_STORAGE': 'file_operations', 'WRITE_EXTERNAL_STORAGE': 'file_operations',
    'MANAGE_EXTERNAL_STORAGE': 'file_operations', 'MOUNT_UNMOUNT_FILESYSTEMS': 'file_operations',
    'ACCESS_FINE_LOCATION': 'location', 'ACCESS_COARSE_LOCATION': 'location',
    'ACCESS_BACKGROUND_LOCATION': 'location',
    'CAMERA': 'media_capture', 'RECORD_AUDIO': 'media_capture', 'BODY_SENSORS': 'media_capture',
    'RECEIVE_BOOT_COMPLETED': 'background_ops', 'WAKE_LOCK': 'background_ops',
    'REQUEST_IGNORE_BATTERY_OPTIMIZATIONS': 'background_ops', 'FOREGROUND_SERVICE': 'background_ops',
    'REQUEST_COMPANION_RUN_IN_BACKGROUND': 'background_ops',
    'REQUEST_COMPANION_USE_DATA_IN_BACKGROUND': 'background_ops',
    'GET_ACCOUNTS': 'device_info', 'READ_CONTACTS': 'device_info', 'WRITE_CONTACTS': 'device_info',
    'AUTHENTICATE_ACCOUNTS': 'device_info',
    'SYSTEM_ALERT_WINDOW': 'overlay', 'DISABLE_KEYGUARD': 'overlay',
    'INSTALL_PACKAGES': 'privileged_ops', 'REQUEST_INSTALL_PACKAGES': 'privileged_ops',
    'DELETE_PACKAGES': 'privileged_ops', 'REQUEST_DELETE_PACKAGES': 'privileged_ops',
    'READ_LOGS': 'privileged_ops', 'QUERY_ALL_PACKAGES': 'privileged_ops',
    'BIND_ACCESSIBILITY_SERVICE': 'accessibility',
    'BIND_NOTIFICATION_LISTENER_SERVICE': 'notifications',
    'BIND_VPN_SERVICE': 'network', 'CHANGE_NETWORK_STATE': 'network',
    'CHANGE_WIFI_STATE': 'network', 'BLUETOOTH_ADMIN': 'network',
    'NFC': 'network',
    'CAPTURE_AUDIO_OUTPUT': 'media_capture', 'MODIFY_PHONE_STATE': 'telephony',
}

# Varlığı uygulamanın zararsız olma ihtimalini artıran izinler
BENIGN_HINT_PERMS = frozenset([
    "USE_FINGERPRINT", "USE_BIOMETRIC", "BLUETOOTH", "NFC",
    "VIBRATE", "FLASHLIGHT", "ACCESS_NOTIFICATION_POLICY",
    "SET_WALLPAPER", "SET_WALLPAPER_HINTS", "EXPAND_STATUS_BAR",
    "KILL_BACKGROUND_PROCESSES", "REORDER_TASKS",
    "GET_PACKAGE_SIZE", "CHANGE_WIFI_MULTICAST_STATE",
    "ACCESS_WIFI_STATE", "ACCESS_NETWORK_STATE", "INTERNET",
    "REQUEST_IGNORE_BATTERY_OPTIMIZATIONS", "FOREGROUND_SERVICE",
    "POST_NOTIFICATIONS", "SCHEDULE_EXACT_ALARM",
    "USE_FULL_SCREEN_INTENT", "REQUEST_COMPANION_PROFILE_WATCH",
    "REQUEST_OBSERVE_COMPANION_DEVICE_PRESENCE",
    "ACTIVITY_RECOGNITION", "READ_MEDIA_IMAGES", "READ_MEDIA_VIDEO",
    "READ_MEDIA_AUDIO", "ACCESS_MEDIA_LOCATION",
])


# Varlığı skoru düşürmesi gereken, yaygın ve güvenilir kütüphaneler
BENIGN_LIBRARIES = frozenset([
    'Landroidx/', 'Lcom/google/android/gms/', 'Lcom/google/firebase/',
    'Lokhttp3/', 'Lkotlin/', 'Lkotlinx/', 'Lcom/facebook/',
    'Lorg/json/', 'Lcom/google/gson/', 'Lcom/google/dagger/',
    'Lcom/squareup/retrofit2/', 'Lcom/squareup/picasso/', 'Lcom/squareup/okio/',
    'Lcom/squareup/moshi/', 'Lcom/squareup/leakcanary/',
    'Lcom/bumptech/glide/', 'Lio/reactivex/', 'Lorg/reactivestreams/',
    'Lcom/google/android/material/', 'Lcom/google/android/play/',
    'Lcom/google/common/', 'Lcom/google/protobuf/',
    'Lcom/airbnb/lottie/', 'Lcom/crashlytics/', 'Lio/fabric/',
    'Lorg/apache/commons/', 'Lorg/slf4j/', 'Lch/qos/logback/',
    'Lcom/jakewharton/', 'Lcom/android/volley/', 'Lcom/android/billingclient/',
    'Lcom/google/zxing/', 'Lcom/journeyapps/barcodescanner/',
    'Lde/hdodenhof/circleimageview/', 'Lcom/github/bumptech/',
    'Lcom/google/mlkit/', 'Lcom/google/ar/', 'Lcom/unity3d/',
    'Lcom/android/installreferrer/', 'Lcom/adjust/sdk/',
    'Lcom/appsflyer/', 'Lcom/mixpanel/android/', 'Lcom/amplitude/',
    'Lcom/segment/analytics/', 'Lcom/stripe/android/',
    'Lcom/paypal/android/', 'Lcom/braintreepayments/',
    'Lcom/twitter/sdk/', 'Lcom/linkedin/android/',
    'Lcom/microsoft/appcenter/', 'Lcom/amazonaws/',
    'Lio/grpc/', 'Lorg/greenrobot/eventbus/', 'Lcom/greenrobot/eventbus/',
    'Lcom/hannesdorfmann/mosby/', 'Lcom/arello_mobile/moxy/',
    'Lbutterknife/', 'Lcom/jakewharton/butterknife/',
    'Lcom/trello/rxlifecycle/', 'Lcom/uber/autodispose/',
    'Lcom/google/android/exoplayer2/', 'Lcom/google/android/datatransport/',
    'Lcom/android/support/', 'Landroid/support/v4/', 'Landroid/support/v7/',
    'Lcom/google/ads/', 'Lcom/google/android/ump/',
    'Lcom/facebook/ads/', 'Lcom/mopub/', 'Lcom/applovin/',
    'Lcom/unity3d/ads/', 'Lcom/vungle/', 'Lcom/chartboost/',
    'Lcom/inmobi/', 'Lcom/ironsource/', 'Lcom/tapjoy/','Lcom/stripe/android/',
    'Lcom/paypal/android/',
    'Lcom/braintreepayments/',
    'Lcom/twitter/sdk/',
    'Lcom/linkedin/android/',
    'Lcom/microsoft/appcenter/',
    'Lcom/amazonaws/',
    'Lio/grpc/',
    'Lorg/greenrobot/eventbus/',
    'Lcom/afollestad/material-dialogs/',
    'Lio/coil-kt/',
    'Lorg/koin/',
    'Lcom/google/android/flexbox/'
])

BENIGN_LIBRARY_WEIGHTS = {
    'Lcom/google/ads/': 3.0,
    'Lcom/facebook/ads/': 3.0,
    'Lcom/mopub/': 3.0,
    'Lcom/applovin/': 3.0,
    'Lcom/unity3d/ads/': 3.0,
    'Lcom/adjust/sdk/': 2.5,
    'Lcom/appsflyer/': 2.5,
    'Lcom/mixpanel/android/': 2.5,      # EKLENDİ
    'Lcom/amplitude/': 2.5,
    'Lcom/segment/analytics/': 2.5,     # EKLENDİ
    'Lcom/stripe/android/': 2.0,        # EKLENDİ
    'Lcom/paypal/android/': 2.0,        # EKLENDİ
    'Lcom/braintreepayments/': 2.0,     # EKLENDİ
    'Lcom/twitter/sdk/': 2.0,           # EKLENDİ
    'Lcom/linkedin/android/': 2.0,      # EKLENDİ
    'Landroidx/': 1.5,
    'Lcom/google/android/material/': 2.0,
    'Lbutterknife/': 2.0,
    'Lcom/bumptech/glide/': 2.0,
    'Lcom/airbnb/lottie/': 2.0,
    'Lkotlin/': 1.0,
    'Lokhttp3/': 1.0,
    'Lcom/google/gson/': 1.0,
}

CRITICAL_APIS_HIGH_CONFIDENCE = (
    'Landroid/app/admin/DevicePolicyManager;->wipeData',
    'dispatchGesture',
    'injectSmsPdu',
    'su -c',
    'pm install',
    'Landroid/os/Process;->killProcess',
    'abortBroadcast',
    'setMobileDataEnabled',
    'setWifiEnabled'
)
# Anlamsal kategorilere atanan risk ağırlıkları
W = {
    "accessibility": 5.0,
    "overlay": 5,
    "notifications": 4.50,
    "dangerous_permissions": 8,
    "sms": 6.5,
    "admin_operations": 6.0,
    "dynamic": 3.5,
    "vpn": 6.5,
    "telephony": 5.5,
    "keylogging": 5,
    "root_detection": 4,
    "banking_targets": 4.5,
    "camera_capture": 3.5,
    "microphone_capture": 3.5,
    "screenshot": 4.5,
    "clipboard": 4.0,
    "webview": 4.5,
    "shell_exec": 4.5,
    "privileged_ops": 4.5,
    "hooking_frameworks": 4.5,
    "package_info": 5.0,
    "emulator_detection": 5,
    "contacts": 4,
    "device_info": 4.0,
    "account": 3.8,
    "classloader_manipulation": 4.5,
    "intent_hijacking": 4.5,
    "crypto": 3.0,
    "network": 2.0,
    "location": 4,
    "anti_debug": 5,
    "native_code": 4.0,
    "content_provider": 0.75,
    "background_ops": 2.0,
    "reflection": 2.5,
    "obfuscation": 4.0,
    "bluetooth": 1.0,
    "nfc": 1,
    "sensor": 1,
    "calendar": 3.2,
    "file_operations": 1.0,
    "sqlite": 1,
    "shared_prefs": 0.5,
    "modern_libs": 0,
    "exfiltration": 8.5,
    "persistence": 4.5,
    "ui_injection": 7.0,
    "data_theft": 8.5,
    "anti_vm": 4.0,         # emulator_detection ile benzer
    "c2_communication": 8.5, # network ile ilişkili ama daha spesifik
    "adware": 1.0,          # Genellikle daha az riskli
    "ransomware": 8.0,       # Yüksek risk
    "spyware": 8.0,         # Yüksek risk
    "permission_abuse": 5.5,
    "analytics": 1.0,
    "payment_sdk": 0.5,     # Yeni: Ödeme SDK'ları genellikle güvenilirdir
    "permissions": 2.0,
    "benign_ui": -0.01,
}